//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unusedCssFinder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unusedCssFinder.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 class=&quot;span5&quot; &gt;[DESCRIPTION]&lt;/h2&gt;.
        /// </summary>
        internal static string Description_template {
            get {
                return ResourceManager.GetString("Description_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/body&gt;
        ///  &lt;/html&gt;.
        /// </summary>
        internal static string Html_bottom {
            get {
                return ResourceManager.GetString("Html_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;link href=&quot;http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;link href=&quot;http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap-responsive.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;script src=&quot;http://code.jquery.com/jquery.js&quot;&gt;&lt;/script&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/js/bootstrap.min.js&quot; &gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;.
        /// </summary>
        internal static string Html_top {
            get {
                return ResourceManager.GetString("Html_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt; &lt;/div&gt;.
        /// </summary>
        internal static string Stylesheet_statistics_bottom {
            get {
                return ResourceManager.GetString("Stylesheet_statistics_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;span12&quot; style=&quot;min-height: 100px;&quot;&gt; &lt;div class=&quot;accordion&quot;&gt;.
        /// </summary>
        internal static string Stylesheet_statistics_top {
            get {
                return ResourceManager.GetString("Stylesheet_statistics_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;accordion-group&quot;&gt;
        ///                         &lt;div class=&quot;accordion-heading&quot;&gt;
        ///                           &lt;a href=&quot;#[UNUSED_ID]&quot; data-parent=&quot;#accordion&quot; data-toggle=&quot;collapse&quot; class=&quot;accordion-toggle collapsed&quot;&gt;
        ///                             &lt;h5&gt;&lt;i class=&quot;icon-plus&quot;&gt;&lt;/i&gt; [UNUSED_DATA_DESCRIPTION] &lt;span class=&quot;pull-right&quot;&gt;Total count: [UNUSED_DATA_COUNT]&lt;/span&gt;&lt;/h5&gt;
        ///                           &lt;/a&gt;                           
        ///                         &lt;/div&gt;
        ///                         &lt;div style=&quot;he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unused_data_template {
            get {
                return ResourceManager.GetString("Unused_data_template", resourceCulture);
            }
        }
    }
}
